### ISSUE TITLE
Schemachange deployment based on tags

### ISSUE THREAD

**Issue by leotizon** [Snowflake-Labs/schemachange#121]
Hello. Currently we trigger our GitHub workflow with push to deployment branches, which works fine.
```
on:
  workflow_dispatch:
  push:
    branches
```

Are you planning to support deployment based on tags?
```
on:
  workflow_dispatch:
    inputs:
      tags:
```

TK!
